version: '3.7'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=wrd-counter
    ports:
      - 3306:3306
  core:
    container_name: core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wrd-counter?createDatabaseIfNotExist=true
    depends_on:
      - db